### ISSUE TITLE
Use params for matching on attributes syntax

### ISSUE THREAD

**Issue by cheerfulstoic** [neo4jrb/neo4j-core#121]
The following doesn't use params:

`Neo4j::Session.query.match(person: {Person: {uuid: 'some_id'}})`

**Comment by subvertallchris** [comment]
This was fixed, wasn't it?

**Comment by cheerfulstoic** [comment]
It wasn't until about a minute ago ;)

**Comment by cheerfulstoic** [comment]
There's still a bit of a question about `set_props` in my mind, though.  See this part of `query_spec.rb`:

```ruby
  describe '#set_props' do
    describe ".set_props('n = {name: \"Brian\"}')" do
      it_generates "SET n = {name: \"Brian\"}"
    end

    describe ".set_props(n: {name: 'Brian', age: 30})" do
      it_generates "SET n = {name: \"Brian\", age: 30}"
    end
  end
```

There's also a question about how this spec would be adressed:

```ruby
    describe '.match(q: {age: 30}).set_props(q: {age: 31})' do
      it_generates 'MATCH (q {age: {q_age}}) SET q = {age: 31}', q_age: 30
    end
```

The spec might pass with a naive implementation, but we would get cypher queries if the queries were to actually run.

**Comment by subvertallchris** [comment]
I'm not sure I understand the first part. Is the question how to handle the case when they provide a string? When a string is given, I'd expect to have to manage params on my own.

The second part... you're trying to avoid a conflict, since that case would create two params with the same name, right? Maybe we could use a `CypherParam` class and use it like this:

```
class CypherParam
  attr_reader :value

  def new(value)
    @value = value
  end
end
```

Then you'd do this:

```
.match(q: {age: CypherParam.new(30)}).set_props(q: {age: CypherParam.new(31)})
```

When the Query object is being converted into a Cypher string, it checks to see if `value.is_a?(CypherParam)`. If true, it creates a unique Cypher param name (maybe just the `object_id` of the param?) to prevent a conflict where there would normally be one?

**Comment by cheerfulstoic** [comment]
Uggg, I really don't like that.  If they're providing us with hashes we should be able to generate param names for them.

Actually, the solutions shouldn't be too bad.  I think we should have an object inside the `Query` object which holds the parameters.  Any time we add a parameter instead of setting a key in a `@params` hash like we're doing now, we call something like `@params_proxy.add_param(proposed_key, value)`.  That would return the actually param key that should be used (probably with a "_#" added to the end if one with the same name already exists) so that we can use it in the cypher query string.

We might want to refactor how this works anyway.  It's a bit odd that if you want to get the `params` for a `Query` object you have to first call `to_cypher` and then call `send(:merge_params)` because it's a private method.

**Comment by subvertallchris** [comment]
I'm not saying they'd be *required* to create new CypherParam objects, it'd just be an option in case they want to manually set a param and/or reuse it without calling `params` and setting the value. It isn't and won't be possible to use a predefined param in a hash, since `match(age: '{my_param}')` would create a new param, but `match(age: my_param)` would work *if* `my_param` is a `CypherParam` object.

I'm also many hours into Java work today, so that's definitely influencing this **a lot**.

**Comment by cheerfulstoic** [comment]
Actually, I don't know if you know that you can do `match(age: '{my_param}')` and since the it starts/ends with squiggly brackets it will assume it's a parameter and pass the string through directly.

**Comment by subvertallchris** [comment]
I feel like I must have known that at some point and forgot.
