### ISSUE TITLE
Neo4j::Node.find_nodes is broken in v4.0.4

### ISSUE THREAD

**Issue by jmnsf** [neo4jrb/neo4j-core#177]
Raises an ArgumentError when calling with correct args.

``` ruby
[30] pry(main)> begin
[30] pry(main)*   Neo4j::Node.find_nodes(:user, u, session)
[30] pry(main)* rescue ArgumentError => e  
[30] pry(main)*   puts e.backtrace
[30] pry(main)* end  
/Users/jmnsf/.rvm/gems/ruby-2.1.4/gems/neo4j-core-4.0.4/lib/neo4j-server/cypher_session.rb:163:in `find_nodes'
/Users/jmnsf/.rvm/gems/ruby-2.1.4/gems/neo4j-core-4.0.4/lib/neo4j/node.rb:199:in `find_nodes'
```

In node.rb:199 there's a call to `session.find_nodes(label, value)` but `find_nodes` is defined in the session as:

``` ruby
def find_nodes(label_name, key, value)
  value = "'#{value}'" if value.is_a? String
  response = _query_or_fail <<-CYPHER
    MATCH (n:`#{label_name}`)
    WHERE n.#{key} = #{value}
    RETURN ID(n)
  CYPHER
  search_result_to_enumerable_first_column(response)
end
```

Yielding a pretty obvious argument mismatch.

**Comment by cheerfulstoic** [comment]
Interesting, I'm not sure I completely understand.  I have a few questions:

 * Is your label `user` or `User`?  (I ask because first letter uppercase is the typical convention)
 * What type of objects are `u` and `session`?

I can see that it's just interpolating `value` into there, but is not good.  I think that this should be replaced by a `Query` chain which will escape/parameterize values for us.

For now, I'd suggest you'd use a query directly, like this:

```ruby
Neo4j::Session.current.query.match(n: :Label).where(n: {key: value}).pluck(:n).first
```

**Comment by jmnsf** [comment]
I'm starting out with Neo4j, just testing a few things and importing data, so I wasn't aware of the conventions; thank you for pointing that out. The label is, indeed, `user`.

`u` would be a ruby hash and session is `Neo4j::Session.current!`.

As you said, the implementation doesn't make a lot of sense. `Neo4j::Node.find_values` receives a `tag` and something identified as `value` which one assumes could be a hash of `{ key => values }` to match in the query, but then the implementation itself is broken.

Like I mentioned, It calls `session.find_nodes(label, value)` when the signature of the method expects 3 arguments: `label`, `key` and `value`.

To my understanding, the session's `find_nodes` method isn't correct either, it should accept a hash of values to match instead of a single key/value pair, and then interpolate those into a MATCH query.

This is just my general, never-used-a-graph-db, opinion though, perhaps this architecture does make sense for a Graph use case and I'm just simply not aware of it due to inexperience.

**Comment by cheerfulstoic** [comment]
Yeah, I'm definitely not defending some of the methods here.  Since making the `Query` class and creating the `neo4j` gem with `ActiveNode` modeling, I'm thinking that a lot of the methods like this on `Session` / `Node` should go (@subvertallchris do you concur?)

So firstly, I think that `find_nodes` doesn't take a hash and a session like you're using it.  It looks like it takes a label and a single key and value.  So if you wanted to find a user by E-Mail, you might do:

```ruby
Neo4j::Node.find_nodes(:user, :email, 'foo@provider.com')
```

If you have a hash of keys/values, I would suggest using `Query` like this (assuming your `Hash` variable is called `attributes`:

```ruby
Neo4j::Session.query.match(var: :user).where(attributes).return(:var) # Will give you an Array of results where you can call `var` on each to get the value

# If you want to get the objects directly:
Neo4j::Session.query.match(var: :user).where(attributes).pluck(:var) # Will give you an Array of `user` nodes
```

And, of course, I always recommend you check out `ActiveNode` in the `neo4j` gem, where you can do something like this:

```ruby
class User
  include Neo4j::ActiveNode
  self.mapped_label_name = 'user' # If you used a capital `U` as your label then this line isn't needed
end
```

Then you could simply do `User.where(attributes).to_a`

**Comment by subvertallchris** [comment]
@cheerfulstoic you basically wrote what I was typing up. :-) I'm not sure this method should go completely -- some basic shortcuts for querying _may_ be worth keeping around -- but they definitely need some love.

@jmnsf, your hunch here is totally correct. I've noticed this method while refactoring and always meant to track it down, see how/where it's used, but never got around to it. We should rework it for the upcoming release.

**Comment by jmnsf** [comment]
@cheerfulstoic I wanted to avoid `ActiveNode` because I'm trying to draw some performance metrics for my specific use case, which means I need to be able to understand/change the Cypher queries being done to the DB, so I ended up on neo4j-core's middleground. I will probably use eventually if I end up using Neo4j.

@subvertallchris I guess the reason I stumbled on this is because it's one of the most stand out methods in the [Node docs](http://neo4jrb.io/neo4j-core/doc/Neo4j/Node.html) and represents something you'd commonly want to do with nodes. When you're starting out and unaware of conventions you kinda just stumble around the docs trying to find ways to do what you want.

Thanks for the help on this guys, did end up doing `session.query` and `session.find_nodes`, working fine through that!

**Comment by dotdotdotpaul** [comment]
This is apparently still a problem in neo4j-core v5.1.11  :P

**Comment by angelacode** [comment]
I get a similar problem with the args mismatch in 6.1.1 for `find_nodes` --

**Comment by cheerfulstoic** [comment]
This is perhaps not a satisfying answer, but `find_nodes` is deprecated as of version 7.0 of `neo4j-core` (final version just released yesterday, see [this blog post](http://neo4jrb.io/blog/2016/12/16/latest-major-releases-of-neo4jrb-gems.html)).

Basically there is an entirely new API in `neo4j-core` which is based around simply making Cypher queries and getting back Node / Relationship / Path objects.  The old API is still around, but `neo4j-core` was doing a lot of different things and we wanted to simplify, especially since you can use `ActiveNode` and `ActiveRel` for higher level abstractions in the `neo4j` gem.

This doesn't mean we wouldn't welcome another level in the Neo4j.rb world which is above `neo4j-core` and below `neo4j`.

Questions / discussion welcome here or on our [Gitter channel](https://gitter.im/neo4jrb/neo4j)
