### ISSUE TITLE
response 403 when generating scaffold

### ISSUE THREAD

**Issue by vikigenius** [neo4jrb/neo4j-core#229]
I already have neo4j server up and running correctly on http://localhost:7474

When i use rails generate scaffold

I get the following error: **neo4j-core-5.1.6/lib/neo4j-server/cypher_session.rb:51:in `open': Server not available on http://localhost:7474 (response code 403) (RuntimeError)**

I tried disabling password authentication and still the same error pops up:
Is it to do with the fact that i am behind a http proxy  (But i do have the bash proxy environment variables set).

Below is my application.rb file:

    require File.expand_path('../boot', __FILE__)

    require "rails"
    # Pick the frameworks you want:
    require "active_model/railtie"
    require "active_job/railtie"
    # require "active_record/railtie"
    require "action_controller/railtie"
    require "action_mailer/railtie"
    require "action_view/railtie"
    require "sprockets/railtie"
    require 'neo4j/railtie'
    require "rails/test_unit/railtie"

    # Require the gems listed in Gemfile, including any gems
    # you've limited to :test, :development, or :production.
    Bundler.require(*Rails.groups)

    module TestdbApp
      class Application < Rails::Application

        config.generators do |g|
          g.orm             :neo4j
        end

        #config.neo4j.session_options = { basic_auth: { username: 'neo4j', password: 'dbpasswd'} } 
        config.neo4j.session_type = :server_db 
        config.neo4j.session_path = 'http://localhost:7474'
        # Configure where the embedded neo4j database should exist
        # Notice embedded db is only available for JRuby
        # config.neo4j.session_type = :embedded_db  # default #server_db
        # config.neo4j.session_path = File.expand_path('neo4j-db', Rails.root)

        # Settings in config/environments/* take precedence over those specified here.
        # Application configuration should go into files in config/initializers
        # -- all .rb files in that directory are automatically loaded.

        # Set Time.zone default to the specified zone and make Active Record auto-convert to this zone.
        # Run "rake -D time" for a list of tasks for finding time zone names. Default is UTC.
        # config.time_zone = 'Central Time (US & Canada)'

        # The default locale is :en and all translations from config/locales/*.rb,yml are auto loaded.
        # config.i18n.load_path += Dir[Rails.root.join('my', 'locales', '*.{rb,yml}').to_s]
        # config.i18n.default_locale = :de
      end
    end

**Comment by cheerfulstoic** [comment]
I'm guessing that it's probably the proxy.  First I should ask: Did you restart after disabling Neo4j's auth?

Can you try it without a proxy to debug?

Also if auth is enabled you may want to log into the neo4j web console and change the default password because Neo4j won't allow you to login via the HTTP endpoints (like Neo4j.rb does) until you've done that

**Comment by vikigenius** [comment]
Well i don't think it's the proxy, instead of http://localhost:7474 i tried http://myipaddress:7474 and it worked. And also it worked only when i disabled password auth, if i do it with auth then it just gets stuck and doesn't proceed at all.

**Comment by cheerfulstoic** [comment]
Oh, interesting, I thought you were saying that it didn't work still when you disabled auth.  That would make some more sense, at least.

Have you yet logged into the Neo4j web console in your browser and set a new password from the default neo4j/neo4j?

**Comment by cheerfulstoic** [comment]
Also, a bug to stick in @subvertallchris or anybody else who cares to think about this:

It might be good for us to catch particularly HTTP status codes and provide help for people on things that they can try.  Maybe text in the error with a suggestion or two, or maybe even just a link to the readthedocs docs so that we can easily update what to do in case of a 401, 403, 404, etc...  GitHub issues provide some search-ability, but it would be nice to have something kind of official.

**Comment by vikigenius** [comment]
Yes, i did change my password from the original from the browser, that was the first thing i did so i don't think that's the problem.

**Comment by cheerfulstoic** [comment]
I'm not really sure what's going on, but since it's working this seems to be working in the non-localhost case I would guess it's an issue with networking and not the gem.  I'm going to close it, but if you find it's an issue with the gem, definitely re-open (or open another issue).

There is also a public Neo4j slack group where somebody else might be able to help you:

http://neo4j.com/blog/public-neo4j-users-slack-group/

I'm on Holiday this week so I have limited time, unfortunately.
