### ISSUE TITLE
Avoid auto-rollback for errors in tests using transactions?

### ISSUE THREAD

**Issue by brucek** [neo4jrb/neo4j-core#258]
So I'm having a problem with neo4jrb, rspec, and [database_cleaner](https://github.com/DatabaseCleaner/database_cleaner) (using transactional cleaning strategy)

Basically my test intentionally causes a `Neo4j::Session::CypherError` (I'm using Cypher constraints to determine whether to insert or retrieve an object by unique key) which I think is then causing the test transaction to immediately abort ["Rollback occurs if an exception is thrown"](https://github.com/neo4jrb/neo4j-core/wiki/Transaction#examples).

Then future `neo4jrb` calls in the same test cause a failure due to the transaction no longer existing.

Is there any way to disable auto-rollback in tests for these kinds of scenarios?  Is that an underlying neo4j thing or something enforced in the driver?

The idiom I am trying to use is:
```ruby
begin
  new_category = Category.find_or_create({ unique_key: val }, {unique_key2: val2)
rescue Neo4j::Session::CypherError => e
  new_category = Category.find_by(unique_key2: val2)
end
```

...I can work around this by turning off transactions just for specs like this, but it would be nice to not have to do that so I can just set something once for all my specs and not have to worry.

Looking at https://github.com/neo4j/neo4j/issues/5806 I'm guessing this is not likely but I figured I would give it a shot.  Thanks guys.

### Runtime information:

Neo4j database version:  2.3.1 - COMMUNITY
`neo4j` gem version: 7.0.2
`neo4j-core` gem version: 6.1.2 (revision: fceaa39021b81411fb4ff3b7da86c22302c77a9b)

**Comment by cheerfulstoic** [comment]
Sorry for the delay, it's been a busy week ;)

So my guess: Neo4j has an interesting quirk in it's transactions where there really isn't such a thing as nested transactions.  In the Java APIs you can nest transactions, but really if the inner transaction fails then the whole outer-most transaction fails.  In the gem when supporting HTTP we simulate the same behavior by allowing nested transactions but by always using the outer-most transaction ID when making queries in transactions.  Since there is (AFAIK) no way in Neo4j via HTTP to say that you want to set up a new transaction which is nested under a previous transaction, this is the only way that I know to handle things.  Bolt may change this somewhat (plans for a Bolt adaptor soon for 8.0 of the gem).  But fundamentally I think that the way Neo4j does transactions prevents you from being able to recover from a error in an inner transaction.

You might ask on the public Slack group to double-check this:

http://neo4j.com/blog/public-neo4j-users-slack-group/

Another option for the gem, perhaps, is to have a `validates` `uniqueness` which would make a check-query first.

**Comment by cheerfulstoic** [comment]
(closing, but happy to have this re-opened if anything that I know about this is wrong)
