### ISSUE TITLE
Gem trips on nil concealing Neo4j error.

### ISSUE THREAD

**Issue by WardCunningham** [neo4jrb/neo4j-core#292]
I am getting an "undefined method" error in neo4j-core code that is trying to classify a db response. This error in ruby code conceals my error in cypher. I would expect the neo4j-core to anticipate the nil value and continue processing my request.

I catch this error with the following code,

```
      # Run the query
      begin
        @results = neo4j.query(@query['query'], @params)
      rescue Exception => e
        @results = []
        @error = e.message + "\n\n" + e.backtrace.join("\n")
      end
```
 which prints this backtrace.
```
undefined method `include?' for nil:NilClass

/Users/ward/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/neo4j-core-7.0.4/lib/neo4j-server/cypher_response.rb:214:in `constraint_error?'
/Users/ward/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/neo4j-core-7.0.4/lib/neo4j-server/cypher_response.rb:209:in `raise_error'
/Users/ward/.rbenv/versions/2.2.2/lib/ruby/gems/2.2.0/gems/neo4j-core-7.0.4/lib/neo4j-server/cypher_session.rb:169:in `query'
/Users/ward/newrelic/el-dorado-ui/el_dorado.rb:130:in `run'
```

Additional information which could be helpful if relevant to your issue:

My helper, neo4j, returns a session:
```
    def neo4j
      @neo4j ||= Neo4j::Session.open(:server_db, ENV['GRAPHDBURL'])
    end
```
My @query['query'] (which I have since corrected) is:
```
match (t:TEAM {name:'Insights'})-[:OWNS]->(s:SERVICE)
optional match (s)<-[x:DEPENDS]-(i:SERVICE)
optional match (s)-[x:DEPENDS]->(o:SERVICE)
return t,s,i,o
order by s.name
```
My @params is empty.

### Code example (inline, gist, or repo)

See above.

### Runtime information:

Neo4j database version: 3.0.3
`neo4j` gem version: 8.0.6
`neo4j-core` gem version: 7.0.4

**Comment by cheerfulstoic** [comment]
Thanks so much for the PR!  I'll integrate and release it, though I should note that it's in our old API.  I'd highly recommend trying the new API (not that it's immune to problems, of course, but just because the old API is deprecated).  You can read about it on the [neo4j-core README](https://github.com/neo4jrb/neo4j-core) as well as in the [upgrade guide](http://neo4jrb.readthedocs.io/en/8.0.x/UpgradeGuide.html) from the docs

**Comment by WardCunningham** [comment]
Thanks for the quick response and also advice on upgrade.

I'm using Sinatra and processing results in my own Ruby code. The Rails/ActiveRecord terminology in the upgrade guide left me lost. Please confirm for me:
- upgrade will depend on using neo4j v3 everywhere
- upgrade will wrap query results in different kinds of objects

**Comment by cheerfulstoic** [comment]
You should actually be able to use back to Neo4j 2.1.5 with version 7.0.3 and up of the `neo4j` gem (see https://github.com/neo4jrb/neo4j#neo4j-version-support).  Of course to use the Bolt adaptor you would need to use Neo4j 3.0 because that's when they introduced support for Bolt.

Results of queries should be wrapped in objects in both the old and the new API.  If you are using just `neo4j-core` it will wrap results in simple `Node`, `Relationship`, and `Path` objects.  If you are using `ActiveNode` / `ActiveRel` in the `neo4j` gem it will wrap the nodes and relationships in `ActiveNode` and `ActiveRel` objects.

Since you're not using Rails and since you're using version 8.0.6 of the `neo4j` gem, one important caveat: before version 8.0.12 of the `neo4j` gem `ActiveNode` and `ActiveRel` objects were **not** being returned from queries unless you were using Rails.  You could make it wrap `ActiveNode` / `ActiveRel` objects by passing in the `wrap_level: :proc` option when creating your session.  After version 8.0.12, this option was automatically added to session used in `ActiveNode` / `ActiveRel`, so you don't need to worry about it if you upgrade.

**Comment by WardCunningham** [comment]
Thanks. I'm prepared to move forward.

**Comment by cheerfulstoic** [comment]
:+1: ;)
